import web_app.routes.error
import web_app.routes.index
import web_app.routes.auth
import web_app.routes.registration
import web_app.routes.upload_avatar
import web_app.routes.dashboard
import web_app.routes.admin
import web_app.routes.group
import web_app.routes.reg_links
import web_app.routes.profile
import web_app.routes.achiv
